sudo: false
language: node_js
cache:
  directories:
  - node_modules
node_js:
  - "4"
  - "5"
env:
  - REACT_ROUTER_VERSION=3
  - REACT_ROUTER_VERSION=4
script:
  - npm run lint
  - ./runTests.sh
after_success:
- cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
